#A
a = list(range(5))
print(a)
#B
b = []
for i in range (5):
    b.append(i)
print(b)
#C
x = list(range(-10, 10))
print(x)
print(min(x), max(x), sum(x))
#D
even_num = list(range(2, 11, 2))
print(even_num[0], even_num[-1])
#E
#Print all the odd numbers from 1 to 9 inclusive in a list, odd_num.
odd_num=list(range(1,9))
print( odd_num[1],odd_num[9])

odd_num=list(range(1,9))
print( odd_num[1],odd_num[9])

#G