print("****************\t **************\t        ")
print("       *\t               *\t       ")
print("       *\t               *\t       ") 
print("       *\t               *\t            ")
print("       *\t               *\t   ")
print("       *\t               *\t    ")
print("       *\t               *\t   ")
print("       *\t               *\t   ")
print("       *\t               *\t   ")
print("       *\t         *****************")
print()